version: "3.6"
services:
  nginx:
    depends_on:
      - client
      - backend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  client:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    restart: on-failure
    container_name: client
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
    restart: on-failure
    container_name: backend
  mongo:
    image: mongo:5
    container_name: "mongo-db"
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo-volume:/data/db
